apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/build: "1"
    app.kubernetes.io/component: worker
    app.kubernetes.io/name: temporal-hello-worker
    app.kubernetes.io/version: v1.0
  name: temporal-hello-worker
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      app.kubernetes.io/name: temporal-hello-worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/build: "1"
        app.kubernetes.io/component: worker
        app.kubernetes.io/name: temporal-hello-worker
        app.kubernetes.io/version: v2.0
    spec:
      initContainers:
      - env:
        - name: TEMPORAL_WORKFLOW_ID
          value: HelloWorkflow
        - name: TEMPORAL_ADDRESS
          value: helloworld.sdvdw.tmprl.cloud:7233
        - name: TEMPORAL_TASK_QUEUE
          value: hello
        - name: TEMPORAL_NAMESPACE
          value: helloworld.sdvdw
        - name: TEMPORAL_CERT_PATH
          value: /etc/certs/tls.crt
        - name: TEMPORAL_KEY_PATH
          value: /etc/certs/tls.key
        name: temporal-replayer
        image: ktenzer/temporal-replayer:v1.0
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/certs
          name: certs
      containers:
      - env:
        - name: TEMPORAL_ADDRESS
          value: helloworld.sdvdw.tmprl.cloud:7233
        - name: TEMPORAL_TASK_QUEUE
          value: hello
        - name: TEMPORAL_NAMESPACE
          value: helloworld.sdvdw
        - name: TEMPORAL_CERT_PATH
          value: /etc/certs/tls.crt
        - name: TEMPORAL_KEY_PATH
          value: /etc/certs/tls.key
        image: ktenzer/temporal-hello-worker:v1.0
        imagePullPolicy: Always
        name: temporal-hello-worker
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/certs
          name: certs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certs
        secret:
          defaultMode: 420
          secretName: temporal-tls
